//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BATS
{
    using System;
    using System.Collections.Generic;
    
    public partial class batssostavstatistika
    {
        public int id_sostava_statistika { get; set; }
        public int id_matcha { get; set; }
        public int id_igroka { get; set; }
        public string statistika_igroka { get; set; }
        public Nullable<int> goli { get; set; }
        public Nullable<int> peredachi { get; set; }
        public Nullable<int> jeltie_kartochki { get; set; }
        public Nullable<int> krasnie_kartochki { get; set; }
        public string komentarii { get; set; }
    
        public virtual batsmatch batsmatch { get; set; }
        public virtual batspolzovatel batspolzovatel { get; set; }
    }
}
