//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BATS
{
    using System;
    using System.Collections.Generic;
    
    public partial class batspolzovatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batspolzovatel()
        {
            this.batssostavstatistika = new HashSet<batssostavstatistika>();
        }
    
        public int id_igroka { get; set; }
        public Nullable<int> id_licenzii { get; set; }
        public string familia { get; set; }
        public string ima { get; set; }
        public string otchestvo { get; set; }
        public System.DateTime data_rojdenia { get; set; }
        public Nullable<int> id_amplua { get; set; }
        public Nullable<int> igrovoi_nomer { get; set; }
        public string login { get; set; }
        public string parol { get; set; }
        public Nullable<int> id_roli { get; set; }
    
        public virtual batsamplua batsamplua { get; set; }
        public virtual batslizenzia batslizenzia { get; set; }
        public virtual batsrol batsrol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batssostavstatistika> batssostavstatistika { get; set; }
    }
}
