//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BATS
{
    using System;
    using System.Collections.Generic;
    
    public partial class batsmatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batsmatch()
        {
            this.batssostavstatistika = new HashSet<batssostavstatistika>();
        }
    
        public int id_matcha { get; set; }
        public Nullable<System.DateTime> data_provedenia { get; set; }
        public string mesto_provedenia { get; set; }
        public string nazvanie_turnira { get; set; }
        public string protivnik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batssostavstatistika> batssostavstatistika { get; set; }
    }
}
