//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BATS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user154_dbEntities : DbContext
    {
        public user154_dbEntities()
            : base("name=user154_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batsamplua> batsamplua { get; set; }
        public virtual DbSet<batslizenzia> batslizenzia { get; set; }
        public virtual DbSet<batsmatch> batsmatch { get; set; }
        public virtual DbSet<batspolzovatel> batspolzovatel { get; set; }
        public virtual DbSet<batsrol> batsrol { get; set; }
        public virtual DbSet<batssostavstatistika> batssostavstatistika { get; set; }
    }
}
